# Generated by Django 5.1 on 2024-08-25 06:27

import store.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=255)),
                ('product_link', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=store.utils.get_image_path)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('game_in_buble', models.CharField(blank=True, max_length=100)),
                ('controller', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Graphics_Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=255)),
                ('product_link', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=store.utils.get_image_path)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('graphics_coprocessor', models.CharField(max_length=100)),
                ('chipset_brand', models.CharField(max_length=100)),
                ('memory_interface', models.CharField(blank=True, max_length=100)),
                ('base_clock_speed', models.CharField(blank=True, max_length=100)),
                ('graphics_card_ram_size', models.CharField(max_length=100)),
                ('item_dimensions', models.CharField(max_length=100)),
                ('item_weight', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=255)),
                ('product_link', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=store.utils.get_image_path)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('processor_brand', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('hard_drive', models.CharField(max_length=100)),
                ('graphics_processor', models.CharField(max_length=100)),
                ('chipset_brand', models.CharField(max_length=100)),
                ('item_model_number', models.CharField(blank=True, max_length=100)),
                ('screen_display_size', models.CharField(max_length=100)),
                ('screen_resolution', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=255)),
                ('product_link', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=store.utils.get_image_path)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('monitor_series', models.CharField(max_length=100)),
                ('monitor_display_size', models.CharField(max_length=100)),
                ('monitor_display_type', models.CharField(max_length=100)),
                ('monitor_display_resolution', models.CharField(max_length=100)),
                ('monitor_display_aspect_ration', models.CharField(max_length=100)),
                ('monitor_display_refresh_rate', models.CharField(max_length=100)),
                ('monitor_hdr', models.CharField(max_length=100)),
                ('monitor_display_ports', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
