# Generated by Django 5.0.4 on 2024-05-01 12:57

import store.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphics_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=store.utils.get_image_path)),
                ('brand', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('graphics_coprocessor', models.CharField(max_length=100)),
                ('chipset_brand', models.CharField(max_length=100)),
                ('graphics_card_ram_size', models.CharField(max_length=100)),
                ('item_dimensions', models.CharField(max_length=100)),
                ('item_weight', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=store.utils.get_image_path)),
                ('brand', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('screen_display_size', models.CharField(max_length=100)),
                ('screen_resolution', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('processor_brand', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('hard_drive', models.CharField(max_length=100)),
                ('graphics_processor', models.CharField(max_length=100)),
                ('chipset_brand', models.CharField(max_length=100)),
                ('item_model_number', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
