# Generated by Django 5.0.4 on 2024-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics_card',
            name='base_clock_speed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='graphics_card',
            name='memory_interface',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='graphics_card',
            name='product_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='laptop',
            name='product_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
